name: Build and push Docker image - Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_and_push_machine_learning_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        with:
          fallback: latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Machine Learning
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Containerfile
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            bertmelis/immich-machine-learning-noavx:${{ steps.previoustag.outputs.tag }}
            bertmelis/immich-machine-learning-noavx:release
            ghcr.io/${{ github.repository_owner }}/immich-machine-learning-noavx:${{ steps.previoustag.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/immich-machine-learning-noavx:release
